'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



''' <summary>
''' _Default class.
''' </summary>
''' <remarks>
''' Auto-generated class.
''' </remarks>

Imports Microsoft.VisualBasic
Imports System
Partial Public Class _Default

	''' <summary>
	''' form1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

	''' <summary>
	''' ASPxPanel1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ASPxPanel1 As Global.DevExpress.Web.ASPxPanel.ASPxPanel

	''' <summary>
	''' ASPxScheduler1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ASPxScheduler1 As Global.DevExpress.Web.ASPxScheduler.ASPxScheduler

	''' <summary>
	''' appointmentDataSource control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected appointmentDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
